sim_api:
  endpoint: "http://sim_api:5000/"
  api_key: ""
  timeout: 30
MAX_CONTENT_LENGTH: 104857600 # 100 MiB
NEXTCLOUD_CLIENT_ID: ""
NEXTCLOUD_SECRET: ""
NEXTCLOUD_API_BASE_URL: ""
NEXTCLOUD_AUTHORIZE_URL: ""
NEXTCLOUD_ACCESS_TOKEN_URL: ""
SECRET_KEY: ""
TEMPLATES_AUTO_RELOAD: true # useful for dev. set this to false in production for a tiny performance boost
SESSION_PERMANENT: True
PERMANENT_SESSION_LIFETIME: 2592000 # one month, but a check during requests might end the session before this time
SESSION_SERIALIZATION_FORMAT: "json" # useful for dev. switch to 'msgpack' in production
SESSION_TYPE: "cachelib" # required for flask_session, don't change this setting
SESSION_COOKIE_SECURE: false # set to true in production
SESSION_COOKIE_NAME: "session" # set to "__Host-session" in production
SESSION_COOKIE_SAMESITE: "Lax" # set to "Strict" in production
